name: tracing

services:
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./conf/tempo.yaml:/etc/tempo.yaml
      - ./data/tempo:/tmp/tempo
    networks:
      - trace-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otelcol-contrib/config.yaml" ]
    volumes:
      - ./conf/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317'  # gRPC 接收器端口
      - "4318:4318" # http 接收器端口
    networks:
      - trace-net
    depends_on:
      - tempo

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=12345678
    ports:
      - "3000:3000"
    networks:
      - trace-net
    depends_on:
      - tempo

networks:
  trace-net:
    driver: bridge
